language: node_js
node_js:
  - '8'
script:
  - npm test
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: george.aidonidis@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
