language: node_js
node_js:
  - 8
services:
  - mongodb
script:
  - npm test
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: dev@thechatshop.com
  api_key: $NPM_TOKEN
  on:
    tags: true
